# Generated by Django 6.0.5 on 2026-06-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
