# Generated by Django 6.0.5 on 2026-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0002_alter_trajet_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='statut_depart',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('parti', 'Parti'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut du départ'),
        ),
    ]
