# Generated by Django 6.0.5 on 2026-05-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('carte_bancaire', 'Carte Bancaire')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('echoue', 'Échoué / Refusé')], default='en_attente', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text="ID unique fourni par l'opérateur", max_length=100, null=True, unique=True)),
                ('telephone_paiement', models.CharField(blank=True, help_text='Numéro utilisé pour le paiement mobile', max_length=20, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
