# Generated by Django 6.0.5 on 2026-06-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
        ('reservations', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_momo', 'MTN Mobile Money'), ('carte', 'Carte bancaire'), ('espece', 'Espèces')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.PositiveIntegerField(help_text='Montant total en FCFA'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='telephone_paiement',
            field=models.CharField(blank=True, help_text='Numéro Mobile Money', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de transaction opérateur', max_length=100, null=True),
        ),
    ]
