# Generated by Django 6.0.5 on 2026-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nombre_places',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de places'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passager_nom',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passager_tel',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
