# Generated by Django 6.0.5 on 2026-05-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_siege', models.PositiveIntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='buses.bus')),
            ],
            options={
                'ordering': ['numero_siege'],
                'unique_together': {('numero_siege', 'bus')},
            },
        ),
    ]
