# Generated by Django 6.0.5 on 2026-05-23 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('gestionnaire', models.OneToOneField(blank=True, limit_choices_to={'role': 'GESTIONNAIRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
