# Generated by Django 6.0.5 on 2026-05-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('capacite', models.PositiveIntegerField()),
                ('type_bus', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('minibus', 'Minibus')], default='standard', max_length=20)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='agences.agence')),
            ],
        ),
    ]
